[project]
name = "ve-connect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ayajlassi987", email = "ayajlassi.2504@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cryptography>=49.0.0",
    "fastapi>=0.138.1",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.49.0",
]

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"
